[package]
name = "settings-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json.workspace = true
settings-core = { path = "../settings-core" }
settings-presentation = { path = "../settings-presentation" }
wasm-bindgen.workspace = true
